language: node_js
node_js:
  - "10"
branches:
  only:
    - website
    - store
    - pdfjs
    - /^renovate.*$/
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - "node_modules"
before_script:
  - echo Branch $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  - npm install
  - bash scripts/test-lib.sh $TRAVIS_BRANCH
script:
  - bash scripts/build-all.sh $TRAVIS_BRANCH
deploy:
  - provider: script
    script: bash scripts/deploy-on-npm.sh $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch:
        - pdfjs
        - store
  - provider: script
    script: bash scripts/push-on-master.sh
    skip_cleanup: true
    on:
      branch:
        - pdfjs
        - store
        - website
  - provider: releases
    user: "$GITHUB_USER"
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      branch:
        - pdfjs
        - store
        - website
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    local-dir: "dist"
    on:
      branch:
        - pdfjs
        - store
        - website
