language: node_js
node_js:
  - "10"
branches:
  only:
    - store
    - pdfjs
    - /^renovate.*$/
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - "node_modules"
before_script:
  - echo Branch $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  - npm install
  - bash scripts/test-lib.sh $TRAVIS_BRANCH
script:
  - bash scripts/build-lib.sh $TRAVIS_BRANCH
deploy:
  - provider: script
    script: bash scripts/deploy-on-npm.sh $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch:
        - pdfjs
        - store
  - provider: script
    script: bash scripts/push-on-master.sh
    skip_cleanup: true
    on:
      branch:
        - pdfjs
        - store
